#!/bin/zsh

FIFO=/tmp/dockery

function send_command() {
    [ -p $FIFO ] && echo "$1" > $FIFO
}


function main() {
    case $ACTION in
        add) send_command "dock" ;;
        remove) send_command "undock" ;;
    esac
}

main
