#!/bin/sh

# MISSING FETURES

# hide mouse coursor when it isn't used
unclutter -root -visible &

# ctrl/esc combo
xcape

# DIMMING UNFOCUSED CLIENTS

# dynamic color temperature adjustment
if [ -e $I3_CONFIG_DIR/redshift ]; then
    source $I3_CONFIG_DIR/redshift &
else # default setup, for gdansk
    redshift -l 54.35:18.65 -m randr -t 5500:4500 -g 0.75:0.75:0.75 &
fi

>> /dev/null which nm-applet && nm-applet &
>> /dev/null which blueberry-tray && blueberry-tray &
